language: ruby
cache: bundler
sudo: false
rvm:
- 2.2.3
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
env:
  global:
  - METRICS_API_USERNAME: odi
  - METRICS_API_PASSWORD: somethingsecret
  - METRICS_API_BASE_URL: https://metrics.theodi.org/
  - HUBOT_USER_LIST: http://hubot.theodi.org/hubot/irc
  - AIRBRAKE_API_KEY: somethingmadeup
  - GITHUB_ORGANISATION: theodi
  - GITHUB_OAUTH_TOKEN: oauth_token
  - GAPPS_USER_EMAIL: nobody@example.com
  - GAPPS_PASSWORD: not_a_real_password
  - CAPSULECRM_ACCOUNT_NAME: ukoditech
  - CAPSULECRM_API_TOKEN: password
  - TRELLO_DEV_KEY: trello_dev_key
  - TRELLO_MEMBER_KEY: trello_member_key
  - GAPPS_SERVICE_ACCOUNT_EMAIL: foo@bar.com
  - secure: C9JVdoqPTdgAxPilbQmF5Rm/4mcmWSB05PffR7KZlAKhwHNTYibc73+H5SX8iEkZZRFpgWe+ujhbrfIPhjpr+/Ymyzw59SDgAHLYf14+YBVHHXZzgoefxZXUw8h3xD/P+KWlVglN9QAyBTIxHcdU+vkFmGYS1SLSdda3pp8ptjw=
  - secure: Heu0yBamaflPLud1Vvx3LtuDXOFlluuAVZmWk3NzzLReoMQE6d0If2TsP1kZXfzKu98IeyItigqKM2VJcaUA8FbzvKa5l+zQ+GY7zkfK2oOSAK9Hp9Q2XGULNBdeJTQSKgKLGci3rn0ww+PzYCkgsDXzyh5WgixolZQJ5voR8Qw=
  - secure: O8dChmuo7Fo9ZM+FN6Q2HZNiPJBCEf58Y92Og015Fax8auT3EHVn0ZI2KldikCdexNWK8slOgiP6TpiYIPmxz9n52DMiRZ+HIn5T0cjccAyvxrRn+pgtuhA/UTfHl0C7wCg1atO1V62vyI6+JPEBlRmcJQ1l8FSmWFUcaZFqhzY=
  - secure: OeI0HpWwRyMbHjqZgEgev3PcOfMDLbp9GPwtpRSYA2tev2Bqp7fHQyudsqtFGpFv1LBCAztYizBb4rRpe6NAOcy8WqrT0KF6sMIoB/tWlxpP4pjqHuFG+/loJryXIhypZ/854j3fffjuV88LyfO/ZfxaAiVKxKp/sdzR5oajZnc=
  - secure: B1KNj4ToLSRCwamro9ZEwY+Is0tHUTzb4qYMpUMqOHGSBa9OXwrafbgfdQAp86FHxoRfxTS4urMdRm6DkllXaYqArJh7zKQzHyPbyIOb6epeSQvMwYrncUrD2ykXStIfBG5/Jlxb3JSlraduDUiGMB5BMTMBcDRPnUjh7aJUYMg=
deploy:
  provider: rubygems
  api_key:
    secure: RcZJA+EL+q9Wrytm1wuF+axx86XDM0Smclkanceueyv0IC9VGS/nCdQBz999ywS6KGZQTVkb0tK2olaAnSI1iIo3LBf+/XIGkt0Kw3fc03PFo3nHl1XQmk/2t/m/HE0SETeNla0HP3zJvzzjeLraug2AX8zi4qhEvVrXzipAHec=
  gem: odi-metrics-tasks
  on:
    tags: true
    branch: master
    repo: theodi/odi-metrics-tasks
